### PR TITLE
Fix potential endless recursion

### LINKED ISSUE #2: Potential Endless Recursion
I have an issue where I see _sths34pf80_odr_safe_set()_ call _sths34pf80_algo_reset()_ which calls _sths34pf80_func_cfg_write()_ which calls _sths34pf80_odr_safe_set()_ etc... 

```
int32_t sths34pf80_algo_reset(stmdev_ctx_t *ctx)
{
  ...
  ret = sths34pf80_func_cfg_write(ctx, STHS34PF80_RESET_ALGO, &tmp, 1);//I suggest probably replacing this line.
 ...
}
```

### PR DESCRIPTION
**Pull request by avisconti**
The sths34pf80_algo_reset() API was done in such away it could call itself and end up in a endless recursion.

Fix #2 and #3.

### CODE REVIEW

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Comment by Rocketmagnet** [comment]
Right, well, the annoying thing is that, while investigating the original code, I managed to get it working. So I undid my changes to confirm that this was what made it work, and it still works.  Now, even re-checking out the original repo it still works! Also, your new code seems to work too.

**Comment by Rocketmagnet** [comment]
Out of interest, were you able to recreate the problem on your own device?

**Comment by avisconti** [comment]
> Right, well, the annoying thing is that, while investigating the original code, I managed to get it working. So I undid my changes to confirm that this was what made it work, and it still works. Now, even re-checking out the original repo it still works! Also, your new code seems to work too.

Very strange... It seems that does not happen all the time

**Comment by avisconti** [comment]
> Out of interest, were you able to recreate the problem on your own device?

No, we never managed to reproduce this issue, but it has been found by you and another user. Moreover, analyzing it seems really that issue may occur.

**Pull request merged**
